# Generated by Django 2.1.5 on 2019-01-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='gradient_color_stop_1',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='entry',
            name='gradient_color_stop_2',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='entry',
            name='gradient_color_stop_3',
            field=models.CharField(max_length=7),
        ),
    ]
