# Generated by Django 2.1.5 on 2019-01-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20190119_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_title',
            field=models.CharField(default='hey jude', max_length=140),
            preserve_default=False,
        ),
    ]
