# Generated by Django 2.1.5 on 2019-01-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_entry_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry',
            field=models.TextField(),
        ),
    ]
